# Generated by Django 5.2.16 on 2026-08-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopGainer',
        ),
        migrations.DeleteModel(
            name='TopLoser',
        ),
    ]
