# Generated by Django 6.0.7 on 2026-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_purpose',
            field=models.CharField(blank=True, choices=[('register', 'Register'), ('forgot_password', 'Forgot Password')], max_length=20, null=True),
        ),
    ]
