# Generated by Django 6.0.7 on 2026-07-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_user_otp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_purpose',
        ),
    ]
