# Generated by Django 5.2.16 on 2026-07-26 16:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('average_buy_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('invested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stock_symbol')},
            },
        ),
    ]
