# Generated by Django 5.2.16 on 2026-07-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_topgainer_toploser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopGainer',
        ),
        migrations.DeleteModel(
            name='TopLoser',
        ),
    ]
