# Generated by Django 6.0.7 on 2026-08-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_topgainer_delete_toploser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remaining_resets',
            field=models.IntegerField(default=3),
        ),
    ]
