# Generated by Django 6.0.7 on 2026-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_last_reset_user_remaining_resets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remaining_resets',
        ),
        migrations.AddField(
            model_name='user',
            name='last_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_reset_count',
            field=models.IntegerField(default=0),
        ),
    ]
