# Generated by Django 5.2.16 on 2026-08-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_last_reset_remove_user_remaining_resets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
