# Generated by Django 6.0.7 on 2026-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopGainerMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_rs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('volume', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-change_percent'],
            },
        ),
        migrations.CreateModel(
            name='TopLoserMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_rs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('volume', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['change_percent'],
            },
        ),
    ]
